# Generated by Django 4.0 on 2022-01-15 14:18

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0015_alter_author_image_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChiefEditor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('family', models.CharField(max_length=50, verbose_name='family ')),
            ],
        ),
        migrations.AlterField(
            model_name='author',
            name='age',
            field=models.IntegerField(default=20, verbose_name='age'),
        ),
        migrations.AlterField(
            model_name='author',
            name='email',
            field=models.EmailField(max_length=100, verbose_name='Email '),
        ),
        migrations.AlterField(
            model_name='author',
            name='image_name',
            field=models.CharField(blank='True', default='nophoto', max_length=200, null=True, verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='author',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Active/Inactive'),
        ),
        migrations.AlterField(
            model_name='author',
            name='register_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date of  regisration '),
        ),
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('title', models.CharField(max_length=100, verbose_name='Name of Publication')),
                ('chiefEditor', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='blog.chiefeditor', verbose_name='ChiefEditor')),
            ],
        ),
        migrations.CreateModel(
            name='Aticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article_title', models.CharField(max_length=300, verbose_name='Article Name')),
                ('slug', models.SlugField(max_length=300)),
                ('article_text', models.TextField(verbose_name='Main Text ')),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='Date of  creation ')),
                ('published_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date of  Publication ')),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name='Date of refreshment ')),
                ('is_active', models.BooleanField(default=False, verbose_name='Active/Inactive')),
                ('status', models.CharField(choices=[('Draft', 'Pishnevis'), ('Publish', 'Published')], default='Draft', max_length=40, verbose_name='Article Situation')),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.author', verbose_name='Writer')),
                ('publication', models.ManyToManyField(to='blog.Publication', verbose_name='PublicationS/ChiefEditor')),
            ],
        ),
    ]
